NLTK (Natural Language Toolkit): uma biblioteca python para trabalhar com linguagem natural:



*   Análise de textos
*   Geração de linguagem natural
*   Compreensão de linguagem natural
*   Tradução automatica, resumo textos etc

Possui comunidade grande e ativa, possui uma vasta documentação

Instalação

pip install nltk

In [1]:
pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

importar no NLTK

In [2]:
import nltk

Para usar algum recurso do NLTK é necessário realizar o download destes recursos: Corpús, corpora e outros recursos necessários para diversas tarefas de PLN

O comando é o nltk.download()

digitar "D" para realizar download

digital "all" para baixar tudo

digitar "q" para fechar

In [3]:
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> l

Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_eng Averaged Perceptron Tagger (JSON)
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] averaged_perceptron_tagger_rus Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] bcp47............... BCP-47 Language Tags
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.............. Chat-80 Data Files
  [ ] city_database....... City Database
  [ ] cmudict............. The Carnegie Mellon Pronouncing Dictionary (0.6)
  [ ] comparative_sentences Comparative Sentence Dataset
Hit Enter to continue:
  [ ] comtrans............ ComTrans Corpus Sample
  [ ] conll2000........... CONLL 2000 Chunking Corpus
  [ ] conll2002........... CONLL 2002 Named Entity Recognition Corpus
  [ ] conll2007........... Dependency Treebanks from CoNLL 2007 (Catalan
                           and Basque Subset)
  [ ] crubadan............ Crubadan Corpus
  [ ] dependency_treebank. Dependency Parsed Treebank
  [ ] dolch............... Dolch Word List
  [ ] english_wordnet..... Open English Wordnet
  [ ] europarl_raw........ Sample European Parliament Proceedings Parallel
                           Corpus
  [ ] extended_omw........ Extended Open Multilingual WordNet
  [ ] floresta............ Portuguese Treebank
  [ ] framenet_v15........ FrameNet 1.5
  [ ] framenet_v17........ FrameNet 1.7
  [ ] gazetteers.......... Gazeteer Lists
  [ ] genesis............. Genesis Corpus
  [ ] gutenberg........... Project Gutenberg Selections
  [ ] ieer................ NIST IE-ER DATA SAMPLE
  [ ] inaugural........... C-Span Inaugural Address Corpus
  [ ] indian.............. Indian Language POS-Tagged Corpus
Hit Enter to continue:
  [ ] jeita............... JEITA Public Morphologically Tagged Corpus (in
                           ChaSen format)
  [ ] kimmo............... PC-KIMMO Data Files
  [ ] knbc................ KNB Corpus (Annotated blog corpus)
  [ ] large_grammars...... Large context-free and feature-based grammars
                           for parser comparison
  [ ] lin_thesaurus....... Lin's Dependency Thesaurus
  [ ] mac_morpho.......... MAC-MORPHO: Brazilian Portuguese news text with
                           part-of-speech tags
  [ ] machado............. Machado de Assis -- Obra Completa
  [ ] masc_tagged......... MASC Tagged Corpus
  [ ] maxent_ne_chunker... ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_ne_chunker_tab ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_treebank_pos_tagger Treebank Part of Speech Tagger (Maximum entropy)
  [ ] maxent_treebank_pos_tagger_tab Treebank Part of Speech Tagger (Maximum entropy)
  [ ] mock_corpus......... Mock Corpus
  [ ] moses_sample........ Moses Sample Models
  [ ] movie_reviews....... Sentiment Polarity Dataset Version 2.0
  [ ] mte_teip5........... MULTEXT-East 1984 annotated corpus 4.0
  [ ] mwa_ppdb............ The monolingual word aligner (Sultan et al.
                           2015) subset of the Paraphrase Database.
Hit Enter to continue:
  [ ] names............... Names Corpus, Version 1.3 (1994-03-29)
  [ ] nombank.1.0......... NomBank Corpus 1.0
  [ ] nonbreaking_prefixes Non-Breaking Prefixes (Moses Decoder)
  [ ] nps_chat............ NPS Chat
  [ ] omw-1.4............. Open Multilingual Wordnet
  [ ] omw................. Open Multilingual Wordnet
  [ ] opinion_lexicon..... Opinion Lexicon
  [ ] panlex_swadesh...... PanLex Swadesh Corpora
  [ ] paradigms........... Paradigm Corpus
  [ ] pe08................ Cross-Framework and Cross-Domain Parser
                           Evaluation Shared Task
  [ ] perluniprops........ perluniprops: Index of Unicode Version 7.0.0
                           character properties in Perl
  [ ] pil................. The Patient Information Leaflet (PIL) Corpus
  [ ] pl196x.............. Polish language of the XX century sixties
  [ ] porter_test......... Porter Stemmer Test Files
  [ ] ppattach............ Prepositional Phrase Attachment Corpus
  [ ] problem_reports..... Problem Report Corpus
  [ ] product_reviews_1... Product Reviews (5 Products)
  [ ] product_reviews_2... Product Reviews (9 Products)
  [ ] propbank............ Proposition Bank Corpus 1.0
Hit Enter to continue:
  [ ] pros_cons........... Pros and Cons
  [ ] ptb................. Penn Treebank
  [ ] punkt............... Punkt Tokenizer Models
  [ ] punkt_tab........... Punkt Tokenizer Models
  [ ] qc.................. Experimental Data for Question Classification
  [ ] reuters............. The Reuters-21578 benchmark corpus, ApteMod
                           version
  [ ] rslp................ RSLP Stemmer (Removedor de Sufixos da Lingua
                           Portuguesa)
  [ ] rte................. PASCAL RTE Challenges 1, 2, and 3
  [ ] sample_grammars..... Sample Grammars
  [ ] semcor.............. SemCor 3.0
  [ ] senseval............ SENSEVAL 2 Corpus: Sense Tagged Text
  [ ] sentence_polarity... Sentence Polarity Dataset v1.0
  [ ] sentiwordnet........ SentiWordNet
  [ ] shakespeare......... Shakespeare XML Corpus Sample
  [ ] sinica_treebank..... Sinica Treebank Corpus Sample
  [ ] smultron............ SMULTRON Corpus Sample
  [ ] snowball_data....... Snowball Data
  [ ] spanish_grammars.... Grammars for Spanish
  [ ] state_union......... C-Span State of the Union Address Corpus
Hit Enter to continue:
  [ ] stopwords........... Stopwords Corpus
  [ ] subjectivity........ Subjectivity Dataset v1.0
  [ ] swadesh............. Swadesh Wordlists
  [ ] switchboard......... Switchboard Corpus Sample
  [ ] tagsets............. Help on Tagsets
  [ ] tagsets_json........ Help on Tagsets (JSON)
  [ ] timit............... TIMIT Corpus Sample
  [ ] toolbox............. Toolbox Sample Files
  [ ] treebank............ Penn Treebank Sample
  [ ] twitter_samples..... Twitter Samples
  [ ] udhr2............... Universal Declaration of Human Rights Corpus
                           (Unicode Version)
  [ ] udhr................ Universal Declaration of Human Rights Corpus
  [ ] unicode_samples..... Unicode Samples
  [ ] universal_tagset.... Mappings to the Universal Part-of-Speech Tagset
  [ ] universal_treebanks_v20 Universal Treebanks Version 2.0
  [ ] vader_lexicon....... VADER Sentiment Lexicon
  [ ] verbnet3............ VerbNet Lexicon, Version 3.3
  [ ] verbnet............. VerbNet Lexicon, Version 2.1
  [ ] webtext............. Web Text Corpus
  [ ] wmt15_eval.......... Evaluation data from WMT15
Hit Enter to continue:
  [ ] word2vec_sample..... Word2Vec Sample
  [ ] wordnet2021......... Open English Wordnet 2021
  [ ] wordnet2022......... Open English Wordnet 2022
  [ ] wordnet31........... Wordnet 3.1
  [ ] wordnet............. WordNet
  [ ] wordnet_ic.......... WordNet-InfoContent
  [ ] words............... Word Lists
  [ ] ycoe................ York-Toronto-Helsinki Parsed Corpus of Old
                           English Prose

Collections:
  [ ] all-corpora......... All the corpora
  [ ] all-nltk............ All packages available on nltk_data gh-pages
                           branch
  [ ] all................. All packages
  [ ] book................ Everything used in the NLTK Book
  [ ] popular............. Popular packages
  [ ] tests............... Packages for running tests
  [ ] third-party......... Third-party data packages

([*] marks installed packages)

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all

    Downloading collection 'all'
       |
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package averaged_perceptron_tagger to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger.zip.
       | Downloading package averaged_perceptron_tagger_eng to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
       | Downloading package averaged_perceptron_tagger_ru to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger_ru.zip.
       | Downloading package averaged_perceptron_tagger_rus to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger_rus.zip.
       | Downloading package basque_grammars to /root/nltk_data...
       |   Unzipping grammars/basque_grammars.zip.
       | Downloading package bcp47 to /root/nltk_data...
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package bllip_wsj_no_aux to /root/nltk_data...
       |   Unzipping models/bllip_wsj_no_aux.zip.
       | Downloading package book_grammars to /root/nltk_data...
       |   Unzipping grammars/book_grammars.zip.
       | Downloading package brown to /root/nltk_data...
       |   Unzipping corpora/brown.zip.
       | Downloading package brown_tei to /root/nltk_data...
       |   Unzipping corpora/brown_tei.zip.
       | Downloading package cess_cat to /root/nltk_data...
       |   Unzipping corpora/cess_cat.zip.
       | Downloading package cess_esp to /root/nltk_data...
       |   Unzipping corpora/cess_esp.zip.
       | Downloading package chat80 to /root/nltk_data...
       |   Unzipping corpora/chat80.zip.
       | Downloading package city_database to /root/nltk_data...
       |   Unzipping corpora/city_database.zip.
       | Downloading package cmudict to /root/nltk_data...
       |   Unzipping corpora/cmudict.zip.
       | Downloading package comparative_sentences to
       |     /root/nltk_data...
       |   Unzipping corpora/comparative_sentences.zip.
       | Downloading package comtrans to /root/nltk_data...
       | Downloading package conll2000 to /root/nltk_data...
       |   Unzipping corpora/conll2000.zip.
       | Downloading package conll2002 to /root/nltk_data...
       |   Unzipping corpora/conll2002.zip.
       | Downloading package conll2007 to /root/nltk_data...
       | Downloading package crubadan to /root/nltk_data...
       |   Unzipping corpora/crubadan.zip.
       | Downloading package dependency_treebank to /root/nltk_data...
       |   Unzipping corpora/dependency_treebank.zip.
       | Downloading package dolch to /root/nltk_data...
       |   Unzipping corpora/dolch.zip.
       | Downloading package english_wordnet to /root/nltk_data...
       |   Unzipping corpora/english_wordnet.zip.
       | Downloading package europarl_raw to /root/nltk_data...
       |   Unzipping corpora/europarl_raw.zip.
       | Downloading package extended_omw to /root/nltk_data...
       | Downloading package floresta to /root/nltk_data...
       |   Unzipping corpora/floresta.zip.
       | Downloading package framenet_v15 to /root/nltk_data...
       |   Unzipping corpora/framenet_v15.zip.
       | Downloading package framenet_v17 to /root/nltk_data...
       |   Unzipping corpora/framenet_v17.zip.
       | Downloading package gazetteers to /root/nltk_data...
       |   Unzipping corpora/gazetteers.zip.
       | Downloading package genesis to /root/nltk_data...
       |   Unzipping corpora/genesis.zip.
       | Downloading package gutenberg to /root/nltk_data...
       |   Unzipping corpora/gutenberg.zip.
       | Downloading package ieer to /root/nltk_data...
       |   Unzipping corpora/ieer.zip.
       | Downloading package inaugural to /root/nltk_data...
       |   Unzipping corpora/inaugural.zip.
       | Downloading package indian to /root/nltk_data...
       |   Unzipping corpora/indian.zip.
       | Downloading package jeita to /root/nltk_data...
       | Downloading package kimmo to /root/nltk_data...
       |   Unzipping corpora/kimmo.zip.
       | Downloading package knbc to /root/nltk_data...
       | Downloading package large_grammars to /root/nltk_data...
       |   Unzipping grammars/large_grammars.zip.
       | Downloading package lin_thesaurus to /root/nltk_data...
       |   Unzipping corpora/lin_thesaurus.zip.
       | Downloading package mac_morpho to /root/nltk_data...
       |   Unzipping corpora/mac_morpho.zip.
       | Downloading package machado to /root/nltk_data...
       | Downloading package masc_tagged to /root/nltk_data...
       | Downloading package maxent_ne_chunker to /root/nltk_data...
       |   Unzipping chunkers/maxent_ne_chunker.zip.
       | Downloading package maxent_ne_chunker_tab to
       |     /root/nltk_data...
       |   Unzipping chunkers/maxent_ne_chunker_tab.zip.
       | Downloading package maxent_treebank_pos_tagger to
       |     /root/nltk_data...
       |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
       | Downloading package maxent_treebank_pos_tagger_tab to
       |     /root/nltk_data...
       |   Unzipping taggers/maxent_treebank_pos_tagger_tab.zip.
       | Downloading package mock_corpus to /root/nltk_data...
       |   Unzipping corpora/mock_corpus.zip.
       | Downloading package moses_sample to /root/nltk_data...
       |   Unzipping models/moses_sample.zip.
       | Downloading package movie_reviews to /root/nltk_data...
       |   Unzipping corpora/movie_reviews.zip.
       | Downloading package mte_teip5 to /root/nltk_data...
       |   Unzipping corpora/mte_teip5.zip.
       | Downloading package mwa_ppdb to /root/nltk_data...
       |   Unzipping misc/mwa_ppdb.zip.
       | Downloading package names to /root/nltk_data...
       |   Unzipping corpora/names.zip.
       | Downloading package nombank.1.0 to /root/nltk_data...
       | Downloading package nonbreaking_prefixes to
       |     /root/nltk_data...
       |   Unzipping corpora/nonbreaking_prefixes.zip.
       | Downloading package nps_chat to /root/nltk_data...
       |   Unzipping corpora/nps_chat.zip.
       | Downloading package omw to /root/nltk_data...
       | Downloading package omw-1.4 to /root/nltk_data...
       | Downloading package opinion_lexicon to /root/nltk_data...
       |   Unzipping corpora/opinion_lexicon.zip.
       | Downloading package panlex_swadesh to /root/nltk_data...
       | Downloading package paradigms to /root/nltk_data...
       |   Unzipping corpora/paradigms.zip.
       | Downloading package pe08 to /root/nltk_data...
       |   Unzipping corpora/pe08.zip.
       | Downloading package perluniprops to /root/nltk_data...
       |   Unzipping misc/perluniprops.zip.
       | Downloading package pil to /root/nltk_data...
       |   Unzipping corpora/pil.zip.
       | Downloading package pl196x to /root/nltk_data...
       |   Unzipping corpora/pl196x.zip.
       | Downloading package porter_test to /root/nltk_data...
       |   Unzipping stemmers/porter_test.zip.
       | Downloading package ppattach to /root/nltk_data...
       |   Unzipping corpora/ppattach.zip.
       | Downloading package problem_reports to /root/nltk_data...
       |   Unzipping corpora/problem_reports.zip.
       | Downloading package product_reviews_1 to /root/nltk_data...
       |   Unzipping corpora/product_reviews_1.zip.
       | Downloading package product_reviews_2 to /root/nltk_data...
       |   Unzipping corpora/product_reviews_2.zip.
       | Downloading package propbank to /root/nltk_data...
       | Downloading package pros_cons to /root/nltk_data...
       |   Unzipping corpora/pros_cons.zip.
       | Downloading package ptb to /root/nltk_data...
       |   Unzipping corpora/ptb.zip.
       | Downloading package punkt to /root/nltk_data...
       |   Unzipping tokenizers/punkt.zip.
       | Downloading package punkt_tab to /root/nltk_data...
       |   Unzipping tokenizers/punkt_tab.zip.
       | Downloading package qc to /root/nltk_data...
       |   Unzipping corpora/qc.zip.
       | Downloading package reuters to /root/nltk_data...
       | Downloading package rslp to /root/nltk_data...
       |   Unzipping stemmers/rslp.zip.
       | Downloading package rte to /root/nltk_data...
       |   Unzipping corpora/rte.zip.
       | Downloading package sample_grammars to /root/nltk_data...
       |   Unzipping grammars/sample_grammars.zip.
       | Downloading package semcor to /root/nltk_data...
       | Downloading package senseval to /root/nltk_data...
       |   Unzipping corpora/senseval.zip.
       | Downloading package sentence_polarity to /root/nltk_data...
       |   Unzipping corpora/sentence_polarity.zip.
       | Downloading package sentiwordnet to /root/nltk_data...
       |   Unzipping corpora/sentiwordnet.zip.
       | Downloading package shakespeare to /root/nltk_data...
       |   Unzipping corpora/shakespeare.zip.
       | Downloading package sinica_treebank to /root/nltk_data...
       |   Unzipping corpora/sinica_treebank.zip.
       | Downloading package smultron to /root/nltk_data...
       |   Unzipping corpora/smultron.zip.
       | Downloading package snowball_data to /root/nltk_data...
       | Downloading package spanish_grammars to /root/nltk_data...
       |   Unzipping grammars/spanish_grammars.zip.
       | Downloading package state_union to /root/nltk_data...
       |   Unzipping corpora/state_union.zip.
       | Downloading package stopwords to /root/nltk_data...
       |   Unzipping corpora/stopwords.zip.
       | Downloading package subjectivity to /root/nltk_data...
       |   Unzipping corpora/subjectivity.zip.
       | Downloading package swadesh to /root/nltk_data...
       |   Unzipping corpora/swadesh.zip.
       | Downloading package switchboard to /root/nltk_data...
       |   Unzipping corpora/switchboard.zip.
       | Downloading package tagsets to /root/nltk_data...
       |   Unzipping help/tagsets.zip.
       | Downloading package tagsets_json to /root/nltk_data...
       |   Unzipping help/tagsets_json.zip.
       | Downloading package timit to /root/nltk_data...
       |   Unzipping corpora/timit.zip.
       | Downloading package toolbox to /root/nltk_data...
       |   Unzipping corpora/toolbox.zip.
       | Downloading package treebank to /root/nltk_data...
       |   Unzipping corpora/treebank.zip.
       | Downloading package twitter_samples to /root/nltk_data...
       |   Unzipping corpora/twitter_samples.zip.
       | Downloading package udhr to /root/nltk_data...
       |   Unzipping corpora/udhr.zip.
       | Downloading package udhr2 to /root/nltk_data...
       |   Unzipping corpora/udhr2.zip.
       | Downloading package unicode_samples to /root/nltk_data...
       |   Unzipping corpora/unicode_samples.zip.
       | Downloading package universal_tagset to /root/nltk_data...
       |   Unzipping taggers/universal_tagset.zip.
       | Downloading package universal_treebanks_v20 to
       |     /root/nltk_data...
       | Downloading package vader_lexicon to /root/nltk_data...
       | Downloading package verbnet to /root/nltk_data...
       |   Unzipping corpora/verbnet.zip.
       | Downloading package verbnet3 to /root/nltk_data...
       |   Unzipping corpora/verbnet3.zip.
       | Downloading package webtext to /root/nltk_data...
       |   Unzipping corpora/webtext.zip.
       | Downloading package wmt15_eval to /root/nltk_data...
       |   Unzipping models/wmt15_eval.zip.
       | Downloading package word2vec_sample to /root/nltk_data...
       |   Unzipping models/word2vec_sample.zip.
       | Downloading package wordnet to /root/nltk_data...
       | Downloading package wordnet2021 to /root/nltk_data...
       | Downloading package wordnet2022 to /root/nltk_data...
       |   Unzipping corpora/wordnet2022.zip.
       | Downloading package wordnet31 to /root/nltk_data...
       | Downloading package wordnet_ic to /root/nltk_data...
       |   Unzipping corpora/wordnet_ic.zip.
       | Downloading package words to /root/nltk_data...
       |   Unzipping corpora/words.zip.
       | Downloading package ycoe to /root/nltk_data...
       |   Unzipping corpora/ycoe.zip.
       |
     Done downloading collection all

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q

True

Vamos criar um dataframe com o pandas

comando import pandas as pd

In [4]:
import pandas as pd

Vamos criar um dataframe com algumas palavras

In [25]:
palavras = pd.DataFrame(['Alunos', 'Faculdade', 'Processamento', 'Chovendo', 'Correr', 'Correndo', 'Corrido','ensolarado', 'indeferido', 'celular', 'tranquilo'], columns=['Sem processamento'])

Visualizar o DataFrame

In [26]:
palavras

   Sem processamento
0             Alunos
1          Faculdade
2      Processamento
3           Chovendo
4             Correr
5           Correndo
6            Corrido
7         ensolarado
8         indeferido
9            celular
10         tranquilo

Stemming

Técnica de PLN que consiste em reduzir as palavras removendo sufixos e prefixos

Agrupa palavras com significados semelhantes sob uma mesma forma (correr, correndo e corrido vão se tornar corr)

para que isso? Facilita o processamento de texto

Usaremos para isso um objeto da classe RSLPStemmer

In [16]:
stemmer = nltk.stem.RSLPStemmer()

RSLPStemmer é uma classe dentro do nltk.stem que possui um algoritmo de stemming para a língua portuguesa

Dentro do algoritmo existem regras que vão seguir caracteristicas morfológicas do portugues para tentar reduzir as palavras de forma precisa

Voltando ao DataFrame, criaremos uma coluna chamada Stemmer. Esta coluna vai receber o resultado do stemmer

Como é palavra por palavra temos que iterar sobre cada palavra da nossa coluna Sem processamento.

In [27]:
palavras['Stemmer'] = [stemmer.stem(palavra) for palavra in palavras['Sem processamento']]

imprimir o resultado

In [28]:
palavras

   Sem processamento   Stemmer
0             Alunos      alun
1          Faculdade  faculdad
2      Processamento   process
3           Chovendo      chov
4             Correr      corr
5           Correndo      corr
6            Corrido      corr
7         ensolarado   ensolar
8         indeferido   indefer
9            celular     celul
10         tranquilo  tranquil

Desafio: testar com outras palavras

**Lematização**

A lematização é um processo de PLN que visa reduzir uma palavra as sua forma base, conhecida como lema. A ideia seria parecida com o Stemming só que com algumas caracteristicas diferentes

* Stemming remove sufixos e prefixos mas muitas vezes não retorna uma palavra existente (corr etc)
* Lematização leva em consideração o significado da palavra e o contexto, tentando chegar a um lema valido - > correndo = correr

Necessario a utilização de um dicionário lexical

No nosso caso baixamos tudo do nltk, poderiamos baixar só o dicionario com o comando a seguir

In [19]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

Vamos usar o nosso dicionario

In [20]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

Criando o lematizador

In [21]:
lematizador = WordNetLemmatizer()

In [22]:
palavra = "running"

lema = lematizador.lemmatize(palavra)
print(lema)

running

Aprimorando o lemaizador indicando a classe gramatical

In [23]:
palavra = "running"

lema = lematizador.lemmatize(palavra, pos=wordnet.VERB)
print(lema)

run

Testem com outras palavras